use Rex -feature => [qw / 1.4 / ];
use Rex::Dondley::ProcessTaskArgs;
use Data::Dumper qw(Dumper);
$Data::Dumper::Purity = 1;
$Data::Dumper::Terse = 1;

# AUTHOR'S NOTE

task 'test1' => sub {
  my $params = process_task_args(\@_, 'one');
  print Dumper $params;
};


task 'test2' => sub {
  my $params = process_task_args(\@_, one => 1, two => 0);
  print Dumper $params;
};
